<?php
/**
 * Created by PhpStorm.
 * User: TuanPV
 * Date: 11/12/2018
 * Time: 1:07 PM
 */

namespace frontend\widgets;


use common\models\News;
use yii\base\Widget;

class IntroduceWidget extends Widget
{
    public $message;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        $introduce = News::find()
            ->andWhere(['type' => News::TYPE_ABOUT])
            ->andWhere(['status' => News::STATUS_ACTIVE])
            ->one();
        return $this->render('introduce-page',['introduce' => $introduce]);
    }
}