<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */

namespace frontend\widgets;

use common\models\News;
use yii\base\Widget;

class LatestDeals extends Widget
{

    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $contents = News::find()
            ->andWhere(['status' => News::STATUS_ACTIVE])
            ->andWhere(['type' => News::TYPE_NEWS])
            ->orderBy(['updated_at' => SORT_DESC])
            ->limit(6)
            ->all();
        return $this->render('latest-deals', [
            'contents' => $contents
        ]);
    }
}
