<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */

namespace frontend\widgets;

use common\models\InfoPublic;
use yii\base\Widget;

class MenuTop extends Widget
{

    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $info = InfoPublic::findOne(InfoPublic::ID_DEFAULT);
        return $this->render('menu-top', ['info' => $info]);
    }
}
