<?php
/**
 * Created by PhpStorm.
 * User: TuanPham
 * Date: 11/19/2016
 * Time: 9:09 PM
 */
namespace frontend\widgets;

use common\models\Category;
use common\models\Content;
use common\models\News;
use DateTime;
use yii\base\Widget;
use Yii;

class WidgetNewContent extends Widget{

    public $message;
    public $project;

    public  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function run()
    {
        if($this->project){
            $news = News::find()
                ->andWhere(['status' => News::STATUS_ACTIVE])
                ->andWhere(['type' => News::TYPE_PRODUCT])
                ->andWhere(['hot' => News::IS_HOT])
                ->orderBy('created_at')
                ->limit(4)
                ->all();
            $name = "Dự án bất động sản hot";
        }else{
            $name = Yii::t('app', 'Tin bất động sản mới');
            $news = News::find()
                ->andWhere(['status' => News::STATUS_ACTIVE])
                ->andWhere(['type' => News::TYPE_NEWS])
                ->orderBy('created_at')
                ->limit(4)
                ->all();
        }
        // sản phẩm sale
        return $this->render('widget-new-content',[
            'news'=>$news,
            'name' => $name
        ]);
    }
}
